name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
projects: ["o92design/1"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report Template
        
        Use this template to report bugs in the Military Coordination System.
        
        Please provide as much detail as possible to help reproduce and fix the issue.

  - type: input
    id: bug-title
    attributes:
      label: Bug Title
      description: A clear, descriptive title for the bug
      placeholder: e.g., "Game loop causes memory leak after 1000 iterations"
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what's happening that shouldn't be happening
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Execute '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: Describe what should happen instead
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this bug?
      options:
        - "core"
        - "model"
        - "engine"
        - "ai"
        - "util"
        - "test"
        - "build"
        - "documentation"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - "critical - system unusable"
        - "high - major functionality broken"
        - "medium - some functionality affected"
        - "low - minor issue"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Windows 11, macOS 14]
        - Java Version: [e.g., Java 21]
        - IDE: [e.g., VS Code, IntelliJ IDEA]
        - Maven Version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs/Stack Trace
      description: If applicable, add error logs or stack traces
      placeholder: Paste any relevant error messages or stack traces here
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Screenshots
        - Related issues
        - Workarounds
        - Impact on development

  - type: checkboxes
    id: bug-checklist
    attributes:
      label: Bug Report Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have provided clear steps to reproduce
          required: true
        - label: I have included error logs/stack traces if available
          required: false
        - label: I have specified the affected component
          required: true
