name: 🎯 Epic
description: Create a new Epic for major feature development
title: "[EPIC] "
labels: ["epic", "enhancement"]
projects: ["o92design/1"]
assignees:
  - o92design
body:
  - type: markdown
    attributes:
      value: |
        ## Epic Template
        
        Use this template to create a major Epic that represents a significant feature or capability in the Military Coordination System.
        
        Epics should be broken down into smaller, manageable tasks that can be completed in 1-3 days each.

  - type: input
    id: epic-title
    attributes:
      label: Epic Title
      description: A clear, descriptive title for this Epic
      placeholder: e.g., "Core Data Models and Structures"
    validations:
      required: true

  - type: textarea
    id: epic-description
    attributes:
      label: Epic Description
      description: Detailed description of what this Epic will accomplish
      placeholder: Describe the overall goal and scope of this Epic
    validations:
      required: true

  - type: textarea
    id: epic-goals
    attributes:
      label: Epic Goals
      description: List the specific goals this Epic will achieve
      placeholder: |
        - Goal 1: Description
        - Goal 2: Description
        - Goal 3: Description
    validations:
      required: true

  - type: textarea
    id: tasks-breakdown
    attributes:
      label: Tasks to Break Down
      description: List the major tasks that need to be created for this Epic
      placeholder: |
        - [ ] Task 1: Description
        - [ ] Task 2: Description
        - [ ] Task 3: Description
        
        Note: Create separate issues for each task and link them to this Epic
    validations:
      required: true

  - type: dropdown
    id: milestone
    attributes:
      label: Milestone
      description: Which milestone does this Epic belong to?
      options:
        - "Milestone 1: Basic Framework"
        - "Milestone 2: Core Functionality"
        - "Milestone 3: Advanced Features"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What's the priority level of this Epic?
      options:
        - "high"
        - "medium"
        - "low"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Define when this Epic will be considered complete
      placeholder: |
        - [ ] All tasks are completed and tested
        - [ ] Documentation is updated
        - [ ] Code meets quality standards
        - [ ] Performance requirements are met
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: List any dependencies on other Epics or external factors
      placeholder: |
        - Depends on Epic #X
        - Requires external library Y
        - Blocked by issue #Z

  - type: input
    id: estimated-duration
    attributes:
      label: Estimated Duration
      description: Rough estimate for Epic completion
      placeholder: e.g., "2-3 weeks"

  - type: checkboxes
    id: epic-checklist
    attributes:
      label: Epic Checklist
      description: Mark items as complete when done
      options:
        - label: Epic goals are clearly defined
          required: true
        - label: Tasks have been identified and will be created as separate issues
          required: true
        - label: Acceptance criteria are specific and measurable
          required: true
        - label: Dependencies have been identified
          required: false
